---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build
      - yarn test:cov
---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-test

server:
  host: backend-api.testenv.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games

  - name: build
    commands:
      - export HOME=/home/w3itch
      - export NVM_DIR="$HOME/.nvm"
      - . "$NVM_DIR/nvm.sh"
      - nvm use node
      - node -v
      - yarn
      - yarn build
      - cp * /home/w3itch/w3itch-backend-build/
      - cd /home/w3itch/w3itch-backend-build

      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 status

trigger:
  branch:
    - testing
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push

---
kind: pipeline
type: ssh
name: promotion-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo promotion production
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: update-config

    commands:
      - echo $VERSION
      - export CONFIG_VERSION = $VERSION
      - export HOME=/home/w3itch
      - echo $CONFIG_VERSION
      - git clone -b $CONFIG_VERSION --single-branch ssh://git@gitea.w3itch.io:10022/w3itch-crafter/w3itch-backend-config.git
      - rm -rf /home/w3itch/w3itch-backend-config-for-rollback
      - cp -r /home/w3itch/w3itch-backend-config /home/w3itch/w3itch-backend-config-for-rollback
      - cp w3itch-backend-config/config/config.production.yaml /home/w3itch/w3itch-backend-config/
  - name: build
    commands:
      - yarn
      - yarn build
      - rm -rf /home/w3itch/w3itch-backend-for-rollback
      - cp -r /home/w3itch/w3itch-backend /home/w3itch/w3itch-backend-for-rollback
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 status

trigger:
  event:
    - promote
  target:
    - production

---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
      - node -v
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: build
    commands:
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 status

trigger:
  branch:
    - main
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push
---
kind: signature
hmac: 507d195c6aab63f91bb736975bc34f0cb7e49c99c90485cf8b3f8094833cd970

...
