---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build
      - yarn test:cov
---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-test

server:
  host: backend-api.testenv.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: build
    commands:
      - export HOME=/home/w3itch
      - source /home/w3itch/.profile
      - source /home/w3itch/.bashrc
      - nvm use node
      - node -v
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 status

trigger:
  branch:
    - dev/w3itch
    - testing
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push

---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
      - node -v
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: build
    commands:
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 status

trigger:
  branch:
    - main
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push
---
kind: signature
hmac: 6731c2f8a9fb2b933f856250156803d9f36c8bc898a1c87a97f49d7f52cb00dc

...
