---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build
      - yarn test:cov
---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-test

server:
  host: backend-api.testenv.w3itch.io
  user: jenkins
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: prepare
    commands:
      - source ～/.bashrc
      - nvm use v16.13.1

  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
      - nvm current
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: build
    commands:
      - yarn
      - yarn build
      - export PM2_HOME=/var/lib/jenkins/.pm2
      - pm2 status

trigger:
  branch:
    - dev/w3itch
    - testing
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push

---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: build
    commands:
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 status

trigger:
  branch:
    - main
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push
---
kind: signature
hmac: b7fbdbda511459a2a44029f6ae67df80a0789d9f29d56bcec59e0a7f26825f99

...
