---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build
      - yarn test:cov
---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-test

server:
  host: backend-api.testenv.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games

  - name: build
    commands:
      - export HOME=/home/w3itch
      - export NVM_DIR="$HOME/.nvm"
      - . "$NVM_DIR/nvm.sh"
      - nvm use node
      - node -v
      - yarn
      - yarn build
      - cp * /home/w3itch/w3itch-backend-build/
      - cd /home/w3itch/w3itch-backend-build

      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 status

trigger:
  branch:
    - testing
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push

---
kind: pipeline
type: ssh
name: promotion-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo promotion production
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: update-config

    commands:
      - echo $VERSION
      - export HOME=/home/w3itch
      - pm2 restart w3itch-backend
      - rm -rf /home/w3itch/w3itch-backend-config-for-rollback
      - cp -r /home/w3itch/w3itch-backend-config /home/w3itch/w3itch-backend-config-for-rollback
      - cp w3itch-backend-config/config/config.production.yaml /home/w3itch/w3itch-backend-config/config/
  - name: build
    commands:
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 stop w3itch-backend
      - rm -rf /home/w3itch/w3itch-backend-for-rollback
      - mv /home/w3itch/w3itch-backend /home/w3itch/w3itch-backend-for-rollback
      - cp /home/w3itch/w3itch-backend-config/config/config.production.yaml /home/w3itch/config/
      - cd .. & cp -r src /home/w3itch/w3itch-backend
      - cp /home/w3itch/config/* /home/w3itch/w3itch-backend/config/
      - cd /home/w3itch/w3itch-backend
      - rm -rf /home/w3itch/w3itch-backend/thirdparty/games
      - ln -s /var/easyrpg/games /home/w3itch/w3itch-backend/thirdparty/games
      - rm -rf /home/w3itch/w3itch-backend/thirdparty/gencache
      - ln -s /var/easyrpg/gencache /home/w3itch/w3itch-backend/thirdparty/gencache
      - rm -rf /home/w3itch/w3itch-backend/thirdparty/downloads
      - ln -s /var/easyrpg/downloads /home/w3itch/w3itch-backend/thirdparty/downloads
      - rm -rf ./thirdparty/rtp
      - cp -r /var/easyrpg/rtp /home/w3itch/w3itch-backend/thirdparty/rtp
      - yarn typeorm:prod migration:run
      - pm2 restart w3itch-backend
trigger:
  event:
    - promote
  target:
    - production

---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
      - node -v
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: build
    commands:
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 status

trigger:
  branch:
    - main
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push
---
kind: signature
hmac: d24c2f715f3926acefd13428fabab81fb9345a6cad921962a91a04a0f725817a

...
