app:
  name: w3itch-backend
  port: 3000
  bodyParser:
    limit: 500mb

db:
  host:
  port:
  username:
  password:
  database:
  charset: utf8mb4_general_ci
  timzone: Z

redis:
  host: localhost
  port: 6379
  pass:

jwt:
  accessTokenName: 'w3itch_access_token'
  refreshTokenName: 'w3itch_refresh_token'
  accessTokenExpires: '20m'
  refreshTokenExpires: '30d'
  issuer:
  algorithm: 'HS512'
  audience: []

cookies:
  accessTokenPath: '/'
  refreshTokenPath: '/accounts/tokens'

cors:
  origins:
    - '*'

swagger:
  enable: true

logger:
  loki:
    enable: false
    url: 'http://127.0.0.1:3100'

cache:
  vcode:
    ttl: 300 # seconds

storage:
  ipfs:
    fleek:
      apiKey:
      apiSecret:
      folder: w3itch/attachment
    gateways:
      - https://ipfs.fleek.co
