app:
  name: w3itch-backend
  port: 3000
  bodyParser:
    limit: 500mb

db:
  host:
  port:
  username:
  password:
  database:
  charset: utf8mb4_general_ci
  timzone: Z

redis:
  host: localhost
  port: 6379
  pass:
  vcode_ttl: 300 # seconds

jwt:
  access_token_name: 'w3itch_access_token'
  refresh_token_name: 'w3itch_refresh_token'
  access_token_expires: '20m'
  refresh_token_expires: '30d'
  issuer:
  algorithm: 'HS512'
  audience: []

cookies:
  access_token_path: '/'
  refresh_token_path: '/accounts/tokens'

cors:
  origins:
    - '*'

swagger:
  enable: true

logger:
  loki:
    enable: false
    url: 'http://127.0.0.1:3100'

storage:
  ipfs:
    fleek:
      apiKey:
      apiSecret:
      folder: w3itch/attachment
    gateways:
      - https://ipfs.fleek.co
